;/***********************************************************************/
/*                                                                     */
/*  FILE        :assignment2.c                                         */
/*  DATE        :Tue, Feb 07, 2012                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :27                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
#include "timers.h"
#include "sfr_r827.h"
#include "lcdlib.h"
#include "serial.h"
#include "lcd.h"

void clock_init(void);
extern volatile unsigned char sec;
extern volatile unsigned char halfsec;
extern volatile unsigned char serial1_message;
volatile unsigned char storage [41] = {0};
volatile unsigned char storage_position = 0;
int i;

/*  This is the main program loop  */
void main(void)
{ clock_init();          // initialise statements
  timer_a_init();
  lcd_init();
  serial_init();
  pd1_3=1;               // set led port to output
  lcd_clear();

  while(1)
  { // LED flasher
    if(0 == sec%2)
      p1_3=1;
    else
      p1_3 = 0;
		
	// scroll LCD
	if(1 == halfsec)
	{ lcd_scroll();
	  halfsec=0;
	}
	 
	// receive serial message, process it using switch case
	if(0 != serial1_message)
	{ switch (serial1_message) 
    {
      case 0x81:                        // line 1 recieved
      lcd_display_top(storage);         // send the message to the top line of LCD
      for (i = 0; 40 > i; i++)          // clear the message buffer and reset position
      storage[i] = 0;
      storage_position = 0;
      break;
		 
      case 0x82:                        // line 2 recieved
      lcd_display_bottom(storage);      // send the message to the bottom line of the LCD
      for (i = 0; 40 > i; i++)          // clear the message buffer and reset position
        storage[i] = 0;
      storage_position = 0;
      break;
		 
      case 0x80:                        // clear display
      lcd_clear();
      break;
		 
      case 0x83:                        // output first line to serial port
      lcd_to_serial();
      break;
		 
      default:	                        // add byte to storage
      storage[storage_position++] = serial1_message;
      break;
    }
	  serial1_message = 0;
    }
  }
}
     
	
void clock_init(void)
{ asm("FCLR I");			  // stop all interrupts
  prc0 = 1;             // enables write to certain addresses (See p126 (pdf data))
  fra00=1;              // high speed on chip oscillator  = on (p102) 
  fra01=1;              // select high speed oscillator as clock (p102)
  ocd2=1;    
  cm06=0;               // (p111) f1             
  prc0 = 0;					    // write disable (p126)
  asm("FSET I");			  // enable interrupts
}