/***********************************************************************/
/*                                                                     */
/*  FILE        :cstartdef.h                                           */
/*  DATE        :Tue, Feb 21, 2012                                     */
/*  DESCRIPTION :define the size of stack.                             */
/*  CPU GROUP   :27                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
#define __STACKSIZE__    0xA0        // user stack
#define __ISTACKSIZE__   0xA0        // interrupt stack
#define __HEAPSIZE__     0x0         // heap size
#define __STANDARD_IO__  0 			 // use standard I/O (ex printf)
#define __WATCH_DOG__    0 			 // When watchdog is made effective after reset, here is set to 1.
