/***********************************************************************/
/*                                                                     */
/*  FILE        :heap.c                                                */
/*  DATE        :Tue, Feb 21, 2012                                     */
/*  DESCRIPTION :define the size of heap.                              */
/*  CPU GROUP   :27                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

/***********************************************************
 *  COMPILER for R8C/Tiny
 *  Copyright(c) 2004 Renesas Technology Corp.
 *  And Renesas Solutions Corp.,All Rights Reserved. 
 *
 * heap.c
 *
 * allocate heap area
 *
 * $Date: 2006/06/13 10:45:18 $
 * $Revision: 1.4 $
 **********************************************************/
#include "typedefine.h"
#include "cstartdef.h"

#if __HEAPSIZE__ != 0
#pragma SECTION	bss	heap

_UBYTE heap_area[__HEAPSIZE__];
#endif
